// <auto-generated />
using FrenchBookApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FrenchBookApp.Migrations
{
    [DbContext(typeof(FrenchBookContext))]
    [Migration("20251021033356_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FrenchBookApp.Paragraph", b =>
                {
                    b.Property<int>("ParagraphId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ParagraphId"));

                    b.Property<string>("EnglishText")
                        .HasColumnType("longtext");

                    b.Property<string>("FrenchText")
                        .HasColumnType("longtext");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("ParagraphId");

                    b.HasIndex("TopicId");

                    b.ToTable("Paragraphs");
                });

            modelBuilder.Entity("FrenchBookApp.Sentence", b =>
                {
                    b.Property<int>("SentenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SentenceId"));

                    b.Property<string>("EnglishText")
                        .HasColumnType("longtext");

                    b.Property<string>("FrenchText")
                        .HasColumnType("longtext");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("SentenceId");

                    b.HasIndex("TopicId");

                    b.ToTable("Sentences");

                    b.HasData(
                        new
                        {
                            SentenceId = 1,
                            EnglishText = "I am speaking to my friend",
                            FrenchText = "Je parle à mon ami",
                            TopicId = 1
                        },
                        new
                        {
                            SentenceId = 2,
                            EnglishText = "He is eating apples",
                            FrenchText = "Il mange des pommes",
                            TopicId = 1
                        },
                        new
                        {
                            SentenceId = 3,
                            EnglishText = "I am going to school",
                            FrenchText = "Je vais à l'école",
                            TopicId = 2
                        },
                        new
                        {
                            SentenceId = 4,
                            EnglishText = "We are going to the beach",
                            FrenchText = "Nous allons à la plage",
                            TopicId = 2
                        },
                        new
                        {
                            SentenceId = 5,
                            EnglishText = "I have a car",
                            FrenchText = "j'ai une voiture",
                            TopicId = 3
                        },
                        new
                        {
                            SentenceId = 6,
                            EnglishText = "They have a dog",
                            FrenchText = "Ils ont un chien",
                            TopicId = 3
                        });
                });

            modelBuilder.Entity("FrenchBookApp.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TopicId"));

                    b.Property<string>("TopicName")
                        .HasColumnType("longtext");

                    b.HasKey("TopicId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            TopicId = 1,
                            TopicName = "-er Verbs"
                        },
                        new
                        {
                            TopicId = 2,
                            TopicName = "Aller"
                        },
                        new
                        {
                            TopicId = 3,
                            TopicName = "Avoir"
                        });
                });

            modelBuilder.Entity("FrenchBookApp.Paragraph", b =>
                {
                    b.HasOne("FrenchBookApp.Topic", "Topic")
                        .WithMany("Paragraphs")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("FrenchBookApp.Sentence", b =>
                {
                    b.HasOne("FrenchBookApp.Topic", "Topic")
                        .WithMany("Sentences")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("FrenchBookApp.Topic", b =>
                {
                    b.Navigation("Paragraphs");

                    b.Navigation("Sentences");
                });
#pragma warning restore 612, 618
        }
    }
}
